-- PQ-AI 3C3B engineering closed-loop delta SQL for DBA approval.
-- Review material only. Application code, Docker, CI, tests, and seed scripts must never run this file automatically.
-- No physical foreign keys are declared; all references are logical *_id fields enforced by application services.
-- Runtime MySQL policy still forbids automatic DELETE/CREATE/DROP/ALTER/TRUNCATE/REPLACE/SET.

CREATE TABLE `process_route` (
  `factory_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 factory.id',
  `route_code` VARCHAR(64) NOT NULL COMMENT '3C3B 工艺路线代码',
  `name` VARCHAR(160) NOT NULL COMMENT '路线名称',
  `version` VARCHAR(32) NOT NULL COMMENT '路线版本',
  `route_type` VARCHAR(24) NOT NULL DEFAULT '3C3B' COMMENT '路线类型',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/ACTIVE/RETIRED',
  `bake_strategy` VARCHAR(120) NULL COMMENT '闪干/烘烤节点追溯策略，不作为 AI 特征',
  `source_uri` VARCHAR(500) NULL COMMENT '批准文件或路线来源',
  `effective_from` TIMESTAMP NULL COMMENT '有效开始时间',
  `effective_to` TIMESTAMP NULL COMMENT '有效结束时间',
  `approved_by` VARCHAR(80) NULL COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_route_ver` (`factory_id`, `route_code`, `version`),
  KEY `idx_process_route_status` (`factory_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 3C3B 工艺路线版本';

CREATE TABLE `process_route_step` (
  `process_route_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 process_route.id',
  `sequence_no` INT NOT NULL COMMENT '路线步骤序号',
  `step_code` VARCHAR(64) NOT NULL COMMENT '步骤代码',
  `step_name` VARCHAR(160) NOT NULL COMMENT '步骤名称',
  `step_type` VARCHAR(32) NOT NULL COMMENT 'SPRAY_STAGE/FLASH/BAKE/INSPECTION/TRANSFER',
  `coating_system` VARCHAR(32) NULL COMMENT 'MIDCOAT/BASECOAT/CLEARCOAT',
  `process_stage` VARCHAR(32) NULL COMMENT '五个批准喷涂执行阶段之一',
  `station_code` VARCHAR(64) NULL COMMENT '站点代码',
  `upstream_step_code` VARCHAR(64) NULL COMMENT '上游步骤代码',
  `downstream_step_code` VARCHAR(64) NULL COMMENT '下游步骤代码',
  `is_ai_feature_source` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否作为 AI 特征来源',
  `control_requirements` JSON NULL COMMENT '控制要求 JSON',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_step_seq` (`process_route_id`, `sequence_no`),
  UNIQUE KEY `uk_route_step_code` (`process_route_id`, `step_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 3C3B 路线步骤';

CREATE TABLE `process_route_applicability` (
  `process_route_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 process_route.id',
  `vehicle_model_id` VARCHAR(36) NULL COMMENT '逻辑引用 vehicle_model.id',
  `color_id` VARCHAR(36) NULL COMMENT '逻辑引用 color.id',
  `status` VARCHAR(24) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/RETIRED',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_model_color` (`process_route_id`, `vehicle_model_id`, `color_id`),
  KEY `idx_route_applicability_status` (`process_route_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 工艺路线适用车型颜色';

CREATE TABLE `file_import_profile` (
  `code` VARCHAR(64) NOT NULL COMMENT '导入 profile 代码',
  `name` VARCHAR(160) NOT NULL COMMENT '导入 profile 名称',
  `version` VARCHAR(32) NOT NULL COMMENT '版本',
  `domain_type` VARCHAR(48) NOT NULL COMMENT 'DURR/BYK/FISCHER/MATERIAL 文件域',
  `parser_type` VARCHAR(32) NOT NULL DEFAULT 'CSV' COMMENT 'CSV/XLSX/JSON/XML/DXQ_EXPORT',
  `target_resource` VARCHAR(80) NOT NULL COMMENT '目标资源',
  `field_mapping` JSON NOT NULL COMMENT '字段映射 JSON',
  `required_fields` JSON NOT NULL COMMENT '必填字段 JSON 数组',
  `validation_rules` JSON NULL COMMENT '校验规则 JSON',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/ACTIVE/RETIRED',
  `source_uri` VARCHAR(500) NULL COMMENT '批准文件 URI',
  `approved_by` VARCHAR(80) NULL COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_import_profile` (`code`, `version`),
  KEY `idx_file_import_profile_domain` (`domain_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 设备/材料文件导入 profile';

CREATE TABLE `file_import_job` (
  `import_no` VARCHAR(64) NOT NULL COMMENT '导入任务号',
  `profile_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 file_import_profile.id',
  `domain_type` VARCHAR(48) NOT NULL COMMENT '文件域',
  `source_filename` VARCHAR(240) NOT NULL COMMENT '源文件名',
  `source_uri` VARCHAR(500) NULL COMMENT '源文件 URI',
  `source_checksum` VARCHAR(128) NULL COMMENT '源文件 checksum',
  `status` VARCHAR(24) NOT NULL DEFAULT 'PREVIEWED' COMMENT 'PREVIEWED/VALIDATED/IMPORTED/FAILED/REPLAYED',
  `row_count` INT NOT NULL DEFAULT 0 COMMENT '总行数',
  `valid_row_count` INT NOT NULL DEFAULT 0 COMMENT '有效行数',
  `failed_row_count` INT NOT NULL DEFAULT 0 COMMENT '失败行数',
  `preview_payload` JSON NULL COMMENT '导入预览 JSON',
  `error_report` JSON NULL COMMENT '错误报告 JSON',
  `submitted_by` VARCHAR(80) NOT NULL DEFAULT 'system' COMMENT '提交人',
  `submitted_at` TIMESTAMP NOT NULL COMMENT '提交时间',
  `imported_at` TIMESTAMP NULL COMMENT '导入完成时间',
  `replay_of_job_id` VARCHAR(36) NULL COMMENT '逻辑引用 file_import_job.id',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_import_job_no` (`import_no`),
  KEY `idx_file_import_job_status` (`domain_type`, `status`, `submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 设备/材料文件导入任务';

CREATE TABLE `measurement_probe` (
  `instrument_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 measurement_instrument.id',
  `code` VARCHAR(64) NOT NULL COMMENT '探头代码',
  `name` VARCHAR(120) NOT NULL COMMENT '探头名称',
  `probe_type` VARCHAR(64) NOT NULL COMMENT '探头类型',
  `serial_no` VARCHAR(120) NULL COMMENT '探头序列号',
  `substrate_type` VARCHAR(80) NULL COMMENT '适用基材',
  `geometry_class` VARCHAR(80) NULL COMMENT '曲率/几何类别',
  `layer_scope` VARCHAR(80) NULL COMMENT '膜层范围',
  `status` VARCHAR(24) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/MAINTENANCE/RETIRED',
  `valid_from` TIMESTAMP NULL COMMENT '有效开始时间',
  `valid_until` TIMESTAMP NULL COMMENT '有效截止时间',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instrument_probe_code` (`instrument_id`, `code`),
  KEY `idx_measurement_probe_status` (`instrument_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 测量探头主数据';

ALTER TABLE `quality_measurement`
  ADD COLUMN `measurement_probe_id` VARCHAR(36) NULL COMMENT '逻辑引用 measurement_probe.id';

CREATE TABLE `measurement_msa_study` (
  `study_no` VARCHAR(64) NOT NULL COMMENT 'MSA 研究编号',
  `instrument_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 measurement_instrument.id',
  `probe_id` VARCHAR(36) NULL COMMENT '逻辑引用 measurement_probe.id',
  `method_id` VARCHAR(36) NULL COMMENT '逻辑引用 measurement_method.id',
  `quality_type` VARCHAR(32) NOT NULL COMMENT '质量类型',
  `metric_code` VARCHAR(64) NOT NULL COMMENT '指标代码',
  `study_type` VARCHAR(32) NOT NULL DEFAULT 'GRR' COMMENT '研究类型',
  `sample_count` INT NOT NULL COMMENT '样件数量',
  `operator_count` INT NOT NULL COMMENT '人员数量',
  `repeat_count` INT NOT NULL COMMENT '重复次数',
  `grr_percent` DECIMAL(18,6) NULL COMMENT 'GRR 百分比',
  `ndc` DECIMAL(18,6) NULL COMMENT 'NDC',
  `result` VARCHAR(24) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PASS/FAIL',
  `study_at` TIMESTAMP NOT NULL COMMENT '研究时间',
  `approved_by` VARCHAR(80) NULL COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `raw_results` JSON NULL COMMENT '原始结果 JSON',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_measurement_msa_study` (`study_no`),
  KEY `idx_measurement_msa_status` (`instrument_id`, `result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 测量系统分析 MSA/GRR';

CREATE TABLE `supplier_mat_submission` (
  `submission_no` VARCHAR(64) NOT NULL COMMENT '供应商提交编号',
  `supplier` VARCHAR(120) NOT NULL COMMENT '供应商',
  `material_batch_id` VARCHAR(36) NULL COMMENT '逻辑引用 material_batch.id',
  `material_code` VARCHAR(64) NOT NULL COMMENT '材料代码',
  `material_name` VARCHAR(120) NULL COMMENT '材料名称',
  `document_type` VARCHAR(32) NOT NULL COMMENT 'COA/TDS/MSDS/DOE',
  `source_uri` VARCHAR(500) NULL COMMENT '源文件 URI',
  `profile_id` VARCHAR(36) NULL COMMENT '逻辑引用 file_import_profile.id',
  `status` VARCHAR(24) NOT NULL DEFAULT 'SUBMITTED' COMMENT 'SUBMITTED/VALIDATED/ACCEPTED/REJECTED/SUPERSEDED',
  `submitted_by` VARCHAR(80) NOT NULL COMMENT '提交人',
  `submitted_at` TIMESTAMP NOT NULL COMMENT '提交时间',
  `reviewed_by` VARCHAR(80) NULL COMMENT '审核人',
  `reviewed_at` TIMESTAMP NULL COMMENT '审核时间',
  `field_values` JSON NULL COMMENT '字段值 JSON',
  `validation_result` JSON NULL COMMENT '校验结果 JSON',
  `deviation_decision` VARCHAR(32) NULL COMMENT '偏差放行决定',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_mat_submission` (`submission_no`),
  KEY `idx_supplier_mat_status` (`supplier`, `status`, `submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 供应商材料文件提交';

CREATE TABLE `supplier_mat_issue` (
  `issue_no` VARCHAR(64) NOT NULL COMMENT '供应商材料问题编号',
  `submission_id` VARCHAR(36) NULL COMMENT '逻辑引用 supplier_mat_submission.id',
  `material_batch_id` VARCHAR(36) NULL COMMENT '逻辑引用 material_batch.id',
  `issue_type` VARCHAR(48) NOT NULL COMMENT '问题类型',
  `severity` VARCHAR(24) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW/MEDIUM/HIGH/CRITICAL',
  `status` VARCHAR(24) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN/WAITING_SUPPLIER/CONTAINED/CLOSED',
  `description` VARCHAR(2000) NOT NULL COMMENT '问题描述',
  `containment_action` VARCHAR(2000) NULL COMMENT '遏制措施',
  `supplier_response` VARCHAR(2000) NULL COMMENT '供应商回复',
  `resolution` VARCHAR(2000) NULL COMMENT '处理结论',
  `owner` VARCHAR(80) NULL COMMENT '责任人',
  `due_at` TIMESTAMP NULL COMMENT '期望完成时间',
  `closed_at` TIMESTAMP NULL COMMENT '关闭时间',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_mat_issue` (`issue_no`),
  KEY `idx_supplier_issue_status` (`status`, `due_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 供应商材料问题';

CREATE TABLE `contribution_validation` (
  `contribution_version_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 point_contribution_version.id',
  `study_no` VARCHAR(64) NOT NULL COMMENT '验证研究编号',
  `target_family` VARCHAR(32) NOT NULL COMMENT '质量目标族',
  `method` VARCHAR(32) NOT NULL COMMENT 'EXPERT/DXQ_SIMULATION/DOE/DEPOSITION_MODEL',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/ACTIVE/RETIRED',
  `sample_count` INT NULL COMMENT '样本数',
  `validation_score` DECIMAL(18,6) NULL COMMENT '验证分数',
  `evidence_uri` VARCHAR(500) NULL COMMENT '证据 URI',
  `evidence_payload` JSON NULL COMMENT '证据 JSON',
  `approved_by` VARCHAR(80) NULL COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contrib_val_study` (`contribution_version_id`, `study_no`),
  KEY `idx_contrib_val_status` (`contribution_version_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 点位贡献验证';

CREATE TABLE `trajectory_segment_geometry` (
  `path_segment_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 trajectory_path_segment.id',
  `geometry_version` VARCHAR(32) NOT NULL COMMENT '几何版本',
  `source_import_job_id` VARCHAR(36) NULL COMMENT '逻辑引用 file_import_job.id',
  `start_position` JSON NULL COMMENT '起点坐标 JSON',
  `end_position` JSON NULL COMMENT '终点坐标 JSON',
  `orientation` JSON NULL COMMENT '姿态 JSON',
  `normal_vector` JSON NULL COMMENT '法向量 JSON',
  `gun_distance` DECIMAL(18,6) NULL COMMENT '喷枪距离',
  `path_spacing` DECIMAL(18,6) NULL COMMENT '路径间距',
  `overlap_ratio` DECIMAL(18,6) NULL COMMENT '重叠率',
  `collision_risk_score` DECIMAL(18,6) NULL COMMENT '碰撞风险分数',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/VALIDATED/ACTIVE/RETIRED',
  `evidence_uri` VARCHAR(500) NULL COMMENT '证据 URI',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_path_segment_geometry` (`path_segment_id`, `geometry_version`),
  KEY `idx_path_geometry_status` (`path_segment_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 轨迹段几何/姿态事实';

CREATE TABLE `quality_issue_task` (
  `task_no` VARCHAR(64) NOT NULL COMMENT '工单编号',
  `title` VARCHAR(180) NOT NULL COMMENT '标题',
  `task_type` VARCHAR(32) NOT NULL DEFAULT 'QUALITY_ISSUE' COMMENT 'QUALITY_ISSUE/PROCESS_DEBUG/SUPPLIER_FEEDBACK/CONTROLLED_TRIAL',
  `status` VARCHAR(24) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN/TRIAGE/IN_TRIAL/WAITING_SUPPLIER/VERIFIED/CLOSED',
  `severity` VARCHAR(24) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW/MEDIUM/HIGH/CRITICAL',
  `factory_id` VARCHAR(36) NULL COMMENT '逻辑引用 factory.id',
  `vehicle_model_id` VARCHAR(36) NULL COMMENT '逻辑引用 vehicle_model.id',
  `color_id` VARCHAR(36) NULL COMMENT '逻辑引用 color.id',
  `production_run_id` VARCHAR(36) NULL COMMENT '逻辑引用 production_run.id',
  `measurement_point_id` VARCHAR(36) NULL COMMENT '逻辑引用 measurement_point.id',
  `quality_measurement_id` VARCHAR(36) NULL COMMENT '逻辑引用 quality_measurement.id',
  `material_batch_id` VARCHAR(36) NULL COMMENT '逻辑引用 material_batch.id',
  `recommendation_id` VARCHAR(36) NULL COMMENT '逻辑引用 recommendation.id',
  `controlled_trial_id` VARCHAR(36) NULL COMMENT '逻辑引用 controlled_trial.id',
  `process_stage` VARCHAR(32) NULL COMMENT '五个批准喷涂执行阶段之一',
  `target_quality_type` VARCHAR(32) NULL COMMENT '目标质量族',
  `target_metric` VARCHAR(64) NULL COMMENT '目标指标',
  `owner_role` VARCHAR(64) NULL COMMENT '责任角色',
  `owner_user_id` VARCHAR(36) NULL COMMENT '逻辑引用 app_user.id',
  `created_by` VARCHAR(80) NOT NULL COMMENT '创建人',
  `due_at` TIMESTAMP NULL COMMENT '期望完成时间',
  `closed_at` TIMESTAMP NULL COMMENT '关闭时间',
  `problem_statement` VARCHAR(2000) NOT NULL COMMENT '问题描述',
  `hypothesis` VARCHAR(2000) NULL COMMENT '工程假设',
  `suspected_cause` VARCHAR(2000) NULL COMMENT '疑似原因',
  `conclusion` VARCHAR(2000) NULL COMMENT '结论',
  `causality_status` VARCHAR(32) NOT NULL DEFAULT 'CORRELATION_ONLY' COMMENT 'CORRELATION_ONLY/RULE_SUPPORTED/DOE_SUPPORTED/VERIFIED_CAUSE',
  `data_quality_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '测量可靠性复核状态',
  `material_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '材料复核状态',
  `durr_execution_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Dürr 执行复核状态',
  `ai_summary` VARCHAR(2000) NULL COMMENT 'AI 摘要',
  `tags` JSON NULL COMMENT '标签 JSON 数组',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quality_issue_task_no` (`task_no`),
  KEY `idx_quality_issue_status` (`status`, `severity`, `created_at`),
  KEY `idx_quality_issue_context` (`factory_id`, `vehicle_model_id`, `color_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 质量问题/工艺调试工单';

CREATE TABLE `quality_issue_evidence` (
  `task_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 quality_issue_task.id',
  `evidence_type` VARCHAR(48) NOT NULL COMMENT '证据类型',
  `source_type` VARCHAR(64) NOT NULL COMMENT '证据来源类型',
  `source_id` VARCHAR(36) NULL COMMENT '证据来源 ID',
  `summary` VARCHAR(2000) NOT NULL COMMENT '证据摘要',
  `evidence_payload` JSON NULL COMMENT '证据 JSON',
  `confidence` DECIMAL(18,6) NULL COMMENT '可信度',
  `causality_status` VARCHAR(32) NOT NULL DEFAULT 'CORRELATION_ONLY' COMMENT '因果状态',
  `created_by` VARCHAR(80) NOT NULL COMMENT '创建人',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_quality_issue_evidence` (`task_id`, `evidence_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 工单证据';

CREATE TABLE `quality_issue_comment` (
  `task_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 quality_issue_task.id',
  `author` VARCHAR(80) NOT NULL COMMENT '作者',
  `role` VARCHAR(64) NULL COMMENT '角色',
  `comment_type` VARCHAR(32) NOT NULL DEFAULT 'COMMENT' COMMENT '记录类型',
  `body` VARCHAR(2000) NOT NULL COMMENT '内容',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_quality_issue_comment` (`task_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 工单协作记录';

CREATE TABLE `eng_knowledge_entry` (
  `entry_code` VARCHAR(64) NOT NULL COMMENT '知识编号',
  `version` VARCHAR(32) NOT NULL COMMENT '版本',
  `title` VARCHAR(180) NOT NULL COMMENT '标题',
  `category` VARCHAR(48) NOT NULL COMMENT '类别',
  `target_quality_type` VARCHAR(32) NULL COMMENT '目标质量族',
  `metric_code` VARCHAR(64) NULL COMMENT '指标代码',
  `symptom_pattern` VARCHAR(2000) NOT NULL COMMENT '症状模式',
  `diagnosis_rule` VARCHAR(2000) NOT NULL COMMENT '诊断规则',
  `recommended_checks` JSON NOT NULL COMMENT '推荐检查 JSON',
  `related_parameters` JSON NOT NULL COMMENT '相关参数 JSON 数组',
  `evidence_level` VARCHAR(32) NOT NULL DEFAULT 'RULE' COMMENT 'RULE/SIMULATION/DOE/CONTROLLED_CHANGE/VERIFIED_CAUSE',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/ACTIVE/RETIRED',
  `source_uri` VARCHAR(500) NULL COMMENT '来源 URI',
  `created_by` VARCHAR(80) NOT NULL COMMENT '创建人',
  `approved_by` VARCHAR(80) NULL COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `remark` VARCHAR(2000) NULL COMMENT '备注',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_eng_knowledge_entry` (`entry_code`, `version`),
  KEY `idx_eng_knowledge_target` (`target_quality_type`, `metric_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 现场诊断知识库';

CREATE TABLE `model_explanation` (
  `model_version_id` VARCHAR(36) NOT NULL COMMENT '逻辑引用 model_version.id',
  `prediction_result_id` VARCHAR(36) NULL COMMENT '逻辑引用 prediction_result.id',
  `explanation_type` VARCHAR(32) NOT NULL COMMENT 'SHAP/SENSITIVITY/UNCERTAINTY/FEATURE_IMPORTANCE',
  `target_metric` VARCHAR(64) NOT NULL COMMENT '目标指标',
  `feature_impacts` JSON NOT NULL COMMENT '特征影响 JSON',
  `sensitivity_grid` JSON NULL COMMENT '敏感性分析 JSON',
  `uncertainty` JSON NULL COMMENT '不确定度 JSON',
  `generated_at` TIMESTAMP NOT NULL COMMENT '生成时间',
  `generated_by` VARCHAR(80) NOT NULL DEFAULT 'system' COMMENT '生成人',
  `id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_model_explanation_target` (`model_version_id`, `explanation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PQ-AI 模型解释与敏感性分析';
