from app.db.base import Base
from app.models import domain  # noqa: F401


def test_core_closed_loop_tables_are_registered() -> None:
    required_tables = {
        "factory",
        "factory_vehicle_model",
        "vehicle_model",
        "vehicle_model_color",
        "color",
        "part",
        "measurement_group",
        "measurement_point",
        "spray_program",
        "spray_program_version",
        "program_vehicle_model",
        "program_color",
        "process_route",
        "process_route_step",
        "process_route_applicability",
        "parameter_constraint_source",
        "brush",
        "brush_parameter",
        "brush_point_contribution",
        "durr_robot",
        "durr_application_controller",
        "durr_rotary_atomizer",
        "program_device_configuration",
        "trajectory_program",
        "trajectory_path_segment",
        "point_contribution_version",
        "point_contribution_entry",
        "contribution_validation",
        "trajectory_segment_geometry",
        "production_device_execution",
        "path_segment_execution",
        "material_batch",
        "file_import_profile",
        "file_import_job",
        "supplier_mat_submission",
        "supplier_mat_issue",
        "mat_char_definition",
        "material_test_method",
        "material_specification",
        "mat_char_applicability",
        "material_batch_test_result",
        "production_run",
        "production_stage_run",
        "actual_parameter",
        "measurement_probe",
        "measurement_msa_study",
        "quality_measurement",
        "quality_metric_definition",
        "quality_metric_value",
        "quality_standard",
        "point_feature_snapshot",
        "dataset_snapshot",
        "dataset_split_member",
        "model_version",
        "model_validation_fold",
        "model_artifact",
        "model_acceptance_decision",
        "model_acceptance_policy",
        "model_applicability_scope",
        "model_ood_policy",
        "prediction_result",
        "diagnosis_result",
        "recommendation",
        "recommendation_action",
        "controlled_trial",
        "program_rollback_execution",
        "closed_loop_evaluation",
        "quality_issue_task",
        "quality_issue_evidence",
        "quality_issue_comment",
        "eng_knowledge_entry",
        "model_explanation",
        "app_user",
        "role",
        "permission",
        "user_role",
        "role_permission",
        "api_key",
        "user_session",
        "audit_log",
    }
    assert required_tables <= set(Base.metadata.tables)


def test_program_versions_support_multiple_models_and_colors() -> None:
    assert "program_vehicle_model" in Base.metadata.tables
    assert "program_color" in Base.metadata.tables
    assert "vehicle_model_id" not in Base.metadata.tables["spray_program"].columns
    assert "color_id" not in Base.metadata.tables["spray_program"].columns
