"""add_recommendation_execution_audit

Revision ID: e7dcc05b83f0
Revises: 69011d99138d
Create Date: 2026-06-10 09:50:46.083224
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e7dcc05b83f0'
down_revision: str | None = '69011d99138d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('executed_by', sa.String(length=80), nullable=True))
    op.add_column('recommendation', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'executed_at')
    op.drop_column('recommendation', 'executed_by')
    # ### end Alembic commands ###
