"""initial_schema

Revision ID: f615aa57c04b
Revises:
Create Date: 2026-06-10 07:41:56.174560
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f615aa57c04b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color_type', sa.String(length=24), nullable=False),
    sa.Column('feature_values', sa.JSON(), nullable=True),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('tds_uri', sa.String(length=500), nullable=True),
    sa.Column('msds_uri', sa.String(length=500), nullable=True),
    sa.Column('coa_uri', sa.String(length=500), nullable=True),
    sa.Column('doe_uri', sa.String(length=500), nullable=True),
    sa.Column('digital_standard', sa.JSON(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('factory',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_owner', sa.String(length=80), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('material_batch',
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=120), nullable=False),
    sa.Column('material_type', sa.String(length=24), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('viscosity', sa.Float(), nullable=True),
    sa.Column('solid_ratio', sa.Float(), nullable=True),
    sa.Column('coa_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_table('model_version',
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('target_metric', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=False),
    sa.Column('artifact_uri', sa.String(length=500), nullable=False),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code', 'version', name='uq_model_version')
    )
    op.create_table('parameter_definition',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('aggregation_method', sa.String(length=32), nullable=False),
    sa.Column('hard_min', sa.Float(), nullable=True),
    sa.Column('hard_max', sa.Float(), nullable=True),
    sa.Column('is_recommendable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('part',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('material', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quality_metric_definition',
    sa.Column('quality_type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quality_type', 'code', name='uq_quality_type_metric_code')
    )
    op.create_table('vehicle_model',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('factory_vehicle_model',
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'vehicle_model_id', name='uq_factory_vehicle_model')
    )
    op.create_table('measurement_group',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('quality_type', sa.String(length=32), nullable=False),
    sa.Column('expected_point_count', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_model_id', 'code', name='uq_group_model_code')
    )
    op.create_table('measurement_point',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('point_type', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('quality_types', sa.JSON(), nullable=False),
    sa.Column('is_match_point', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_model_id', 'code', name='uq_point_model_code')
    )
    op.create_table('production_run',
    sa.Column('run_no', sa.String(length=64), nullable=False),
    sa.Column('body_no', sa.String(length=64), nullable=True),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('color_id', sa.String(length=36), nullable=False),
    sa.Column('shift', sa.String(length=24), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_no')
    )
    op.create_index(op.f('ix_production_run_body_no'), 'production_run', ['body_no'], unique=False)
    op.create_index('ix_production_run_context', 'production_run', ['factory_id', 'vehicle_model_id', 'color_id'], unique=False)
    op.create_table('spray_program',
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('process_stage', sa.String(length=32), nullable=False),
    sa.Column('station_code', sa.String(length=32), nullable=False),
    sa.Column('station_name', sa.String(length=120), nullable=False),
    sa.Column('robot_model', sa.String(length=120), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'program_code', name='uq_factory_program_code')
    )
    op.create_table('vehicle_model_color',
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('color_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_model_id', 'color_id', name='uq_vehicle_model_color')
    )
    op.create_table('measurement_group_point',
    sa.Column('measurement_group_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_group_id'], ['measurement_group.id'], ),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_group_id', 'measurement_point_id', name='uq_group_point')
    )
    op.create_table('point_feature_snapshot',
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=False),
    sa.Column('feature_values', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_run_id', 'measurement_point_id', 'feature_set_version', name='uq_run_point_feature_version')
    )
    op.create_table('prediction_result',
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_run_point', 'prediction_result', ['production_run_id', 'measurement_point_id'], unique=False)
    op.create_table('quality_measurement',
    sa.Column('data_no', sa.String(length=64), nullable=False),
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_group_id', sa.String(length=36), nullable=True),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('quality_type', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=24), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measured_by', sa.String(length=80), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('status_score', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_group_id'], ['measurement_group.id'], ),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_no')
    )
    op.create_index('ix_quality_point_time', 'quality_measurement', ['measurement_point_id', 'measured_at'], unique=False)
    op.create_table('quality_standard',
    sa.Column('standard_no', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('standard_type', sa.String(length=24), nullable=False),
    sa.Column('quality_type', sa.String(length=32), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=True),
    sa.Column('color_id', sa.String(length=36), nullable=True),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_standard_match', 'quality_standard', ['quality_type', 'metric_code', 'vehicle_model_id', 'color_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('recommendation_no', sa.String(length=64), nullable=False),
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('target_quality_type', sa.String(length=32), nullable=False),
    sa.Column('target_metric', sa.String(length=64), nullable=False),
    sa.Column('diagnosis_summary', sa.Text(), nullable=False),
    sa.Column('predicted_improvement', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('constraints_checked', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_no')
    )
    op.create_index('ix_recommendation_status', 'recommendation', ['status', 'created_at'], unique=False)
    op.create_table('spray_program_version',
    sa.Column('spray_program_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('is_master_sample', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['spray_program_id'], ['spray_program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spray_program_id', 'version', name='uq_program_version')
    )
    op.create_table('brush',
    sa.Column('program_version_id', sa.String(length=36), nullable=False),
    sa.Column('brush_no', sa.String(length=32), nullable=False),
    sa.Column('brush_table_no', sa.String(length=64), nullable=False),
    sa.Column('spray_position', sa.String(length=120), nullable=True),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['program_version_id'], ['spray_program_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_version_id', 'brush_no', name='uq_program_brush_no')
    )
    op.create_table('closed_loop_evaluation',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('verified_value', sa.Float(), nullable=False),
    sa.Column('actual_improvement', sa.Float(), nullable=False),
    sa.Column('is_effective', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(length=80), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', name='uq_recommendation_evaluation')
    )
    op.create_table('diagnosis_result',
    sa.Column('prediction_result_id', sa.String(length=36), nullable=True),
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('factor_contributions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('causality_status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_result.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_stage_run',
    sa.Column('production_run_id', sa.String(length=36), nullable=False),
    sa.Column('process_stage', sa.String(length=32), nullable=False),
    sa.Column('program_version_id', sa.String(length=36), nullable=False),
    sa.Column('material_batch_id', sa.String(length=36), nullable=True),
    sa.Column('actual_parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_run.id'], ),
    sa.ForeignKeyConstraint(['program_version_id'], ['spray_program_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_run_id', 'process_stage', name='uq_run_stage')
    )
    op.create_table('program_color',
    sa.Column('program_version_id', sa.String(length=36), nullable=False),
    sa.Column('color_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['program_version_id'], ['spray_program_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_version_id', 'color_id', name='uq_program_color')
    )
    op.create_table('program_vehicle_model',
    sa.Column('program_version_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_model_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_version_id'], ['spray_program_version.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_version_id', 'vehicle_model_id', name='uq_program_model')
    )
    op.create_table('quality_metric_value',
    sa.Column('measurement_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('corrected_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['quality_measurement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_id', 'metric_code', name='uq_measurement_metric')
    )
    op.create_table('recommendation_action',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('process_stage', sa.String(length=32), nullable=False),
    sa.Column('brush_no', sa.String(length=32), nullable=True),
    sa.Column('parameter_code', sa.String(length=64), nullable=False),
    sa.Column('parameter_name', sa.String(length=120), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('recommended_value', sa.Float(), nullable=False),
    sa.Column('executed_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('hard_min', sa.Float(), nullable=True),
    sa.Column('hard_max', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_parameter',
    sa.Column('production_stage_run_id', sa.String(length=36), nullable=False),
    sa.Column('brush_id', sa.String(length=36), nullable=True),
    sa.Column('parameter_definition_id', sa.String(length=36), nullable=True),
    sa.Column('parameter_code', sa.String(length=64), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brush_id'], ['brush.id'], ),
    sa.ForeignKeyConstraint(['parameter_definition_id'], ['parameter_definition.id'], ),
    sa.ForeignKeyConstraint(['production_stage_run_id'], ['production_stage_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actual_parameter_stage_code', 'actual_parameter', ['production_stage_run_id', 'parameter_code'], unique=False)
    op.create_table('brush_parameter',
    sa.Column('brush_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_definition_id', sa.String(length=36), nullable=True),
    sa.Column('parameter_code', sa.String(length=64), nullable=False),
    sa.Column('parameter_name', sa.String(length=120), nullable=False),
    sa.Column('configured_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('soft_min', sa.Float(), nullable=True),
    sa.Column('soft_max', sa.Float(), nullable=True),
    sa.Column('hard_min', sa.Float(), nullable=True),
    sa.Column('hard_max', sa.Float(), nullable=True),
    sa.Column('is_recommendable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brush_id'], ['brush.id'], ),
    sa.ForeignKeyConstraint(['parameter_definition_id'], ['parameter_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brush_id', 'parameter_code', name='uq_brush_parameter')
    )
    op.create_table('brush_point_contribution',
    sa.Column('brush_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_point_id', sa.String(length=36), nullable=False),
    sa.Column('overlap_ratio', sa.Float(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brush_id'], ['brush.id'], ),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brush_id', 'measurement_point_id', name='uq_brush_point')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brush_point_contribution')
    op.drop_table('brush_parameter')
    op.drop_index('ix_actual_parameter_stage_code', table_name='actual_parameter')
    op.drop_table('actual_parameter')
    op.drop_table('recommendation_action')
    op.drop_table('quality_metric_value')
    op.drop_table('program_vehicle_model')
    op.drop_table('program_color')
    op.drop_table('production_stage_run')
    op.drop_table('diagnosis_result')
    op.drop_table('closed_loop_evaluation')
    op.drop_table('brush')
    op.drop_table('spray_program_version')
    op.drop_index('ix_recommendation_status', table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index('ix_standard_match', table_name='quality_standard')
    op.drop_table('quality_standard')
    op.drop_index('ix_quality_point_time', table_name='quality_measurement')
    op.drop_table('quality_measurement')
    op.drop_index('ix_prediction_run_point', table_name='prediction_result')
    op.drop_table('prediction_result')
    op.drop_table('point_feature_snapshot')
    op.drop_table('measurement_group_point')
    op.drop_table('vehicle_model_color')
    op.drop_table('spray_program')
    op.drop_index('ix_production_run_context', table_name='production_run')
    op.drop_index(op.f('ix_production_run_body_no'), table_name='production_run')
    op.drop_table('production_run')
    op.drop_table('measurement_point')
    op.drop_table('measurement_group')
    op.drop_table('factory_vehicle_model')
    op.drop_table('vehicle_model')
    op.drop_table('quality_metric_definition')
    op.drop_table('part')
    op.drop_table('parameter_definition')
    op.drop_table('model_version')
    op.drop_table('material_batch')
    op.drop_table('factory')
    op.drop_table('color')
    # ### end Alembic commands ###
